C:\\Users\\Zunaira\\Documents\\3rd Semester\\Data Structures\\Data Project\\NCHS_ - _Leading_Causes_of_Death__United_States_8.csv"
"C:\\Users\\Zunaira\\Documents\\3rd Semester\\Data Structures\\Data Project\\NCHS_-_Leading_Causes_of_Death__United_States_9.csv"
"C:\\Users\\Zunaira\\Documents\\3rd Semester\\Data Structures\\Data Project\\NCHS_-_Leading_Causes_of_Death__United_States_10.csv"
"C:\\Users\\Zunaira\\Documents\\3rd Semester\\Data Structures\\Data Project\\NCHS_-_Leading_Causes_of_Death__United_States_1.csv"
"C:\\Users\\Zunaira\\Documents\\3rd Semester\\Data Structures\\Data Project\\NCHS_-_Leading_Causes_of_Death__United_States_2.csv"
"C:\\Users\\Zunaira\\Documents\\3rd Semester\\Data Structures\\Data Project\\NCHS_-_Leading_Causes_of_Death__United_States_3.csv"
"C:\\Users\\Zunaira\\Documents\\3rd Semester\\Data Structures\\Data Project\\NCHS_-_Leading_Causes_of_Death__United_States_4.csv"
"C:\\Users\\Zunaira\\Documents\\3rd Semester\\Data Structures\\Data Project\\NCHS_-_Leading_Causes_of_Death__United_States_5.csv"
"C:\\Users\\Zunaira\\Documents\\3rd Semester\\Data Structures\\Data Project\\NCHS_-_Leading_Causes_of_Death__United_States_6.csv"
"C:\\Users\\Zunaira\\Documents\\3rd Semester\\Data Structures\\Data Project\\NCHS_-_Leading_Causes_of_Death__United_States_7.csv"